export const UPDATE_SCREEN_HEIGHT = "UPDATE_SCREEN_HEIGHT";

export const UPDATE_DARKMODE = "UPDATE_DARKMODE";

export const UPDATE_DARKMODETOGGLE = "UPDATE_DARKMODETOGGLE";

export const UPDATE_REMEMBERMETOGGLE = "UPDATE_REMEMBERMETOGGLE";

export const UPDATE_GLOBAL_COLOR = "UPDATE_GLOBAL_COLOR";

export const UPDATE_GLOBAL_COLOR_UPDATE_COLOR1ONLY =
  "UPDATE_GLOBAL_COLOR_UPDATE_COLOR1ONLY";

export const ACTIVATE_GLOBAL_LOADER = "ACTIVATE_GLOBAL_LOADER";

export const HIDE_GLOBAL_LOADER = "HIDE_GLOBAL_LOADER";

export const CHANGE_OPTIONS_TOP = "CHANGE_OPTIONS_TOP";

export const CHANGE_NAV = "CHANGE_NAV";

export const CHANGE_NAV_FILTER = "CHANGE_NAV_FILTER";

export const CHANGE_NAV_CROP = "CHANGE_NAV_CROP";

export const UPDATE_SNAP = "UPDATE_SNAP";

export const UPDATE_ALERT = "UPDATE_ALERT";

export const UPDATE_LOADER = "UPDATE_LOADER";

export const UPDATE_HISCROLL = "UPDATE_HISCROLL";

export const UPDATE_COMMENT_HISCROLL = "UPDATE_COMMENT_HISCROLL";

export const HIPOSTDATA_FROMCOM = "HIPOSTDATA_FROMCOM";

export const UPDATE_COMSCROLL = "UPDATE_COMSCROLL";

export const UPDATE_HIREACTION_TYPE = "UPDATE_HIREACTION_TYPE";

export const CHANGE_UPLOAD_DATA = "CHANGE_UPLOAD_DATA";

export const UPDATE_INTERACT = "UPDATE_INTERACT";

export const UPDATE_MenuData = "UPDATE_MenuData";

export const UPDATE_MenuNav = "UPDATE_MenuNav";

export const UPDATE_pagenum = "UPDATE_pagenum";


